### PR TITLE
Splash Screen

### PR DESCRIPTION
**Pull request by Vrushti24**

### CODE REVIEW

**Comment by jaisadana1999** [comment]
Please provide screenshot of the Splash Screen that you have made
@Vrushti24

**Comment by Vrushti24** [comment]
I m so sorry for delay actually something is wrong on my laptop but I will
send it in half an hour once again sorry for delay.

**Comment by jaisadana1999** [comment]
Sure @Vrushti24

**Comment by Vrushti24** [comment]
https://user-images.githubusercontent.com/71961160/106382858-453b2a80-63e8-11eb-9e39-5e40315dde71.mp4

**Comment by Vrushti24** [comment]
did u like this? @jaisadana1999

**Comment by jaisadana1999** [comment]
Looking Great @Vrushti24 
So I have merged your PR

**Comment by Vrushti24** [comment]
Thank you!

**Pull request merged**
